# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "accounts", :force => true do |t|
    t.column "number", :string, :limit => 50, :default => "", :null => false
    t.column "pin", :string, :limit => 50, :default => "", :null => false
    t.column "balance", :integer, :default => 0, :null => false
    t.column "created_on", :timestamp, :limit => 14
    t.column "updated_on", :timestamp, :limit => 14
    t.column "last_login", :datetime
    t.column "logins", :integer, :default => 0, :null => false
    t.column "attempts_today", :integer, :default => 0, :null => false
    t.column "attempts_total", :integer, :default => 0, :null => false
  end

  create_table "coupons", :force => true do |t|
    t.column "voucher", :string, :limit => 50, :default => "", :null => false
    t.column "price", :integer, :default => 0, :null => false
    t.column "product_id", :integer, :default => 0, :null => false
    t.column "account_id", :integer
    t.column "used", :string, :limit => 1, :default => "N", :null => false
    t.column "created_on", :timestamp, :limit => 14
    t.column "updated_on", :timestamp, :limit => 14
    t.column "used_on", :datetime
  end

  add_index "coupons", ["voucher"], :name => "vouchers", :unique => true
  add_index "coupons", ["product_id"], :name => "product"
  add_index "coupons", ["account_id"], :name => "accounts"

  create_table "issuers", :force => true do |t|
    t.column "name", :string, :limit => 50, :default => "", :null => false
  end

  create_table "products", :force => true do |t|
    t.column "name", :string, :limit => 50, :default => "", :null => false
    t.column "price", :integer, :default => 0, :null => false
    t.column "issuer_id", :integer, :default => 0, :null => false
  end

  add_index "products", ["issuer_id"], :name => "issuers"

end
